spring:
  datasource:
    url: jdbc:h2:mem:clientsdb
    driver-class-name: org.h2.Driver
    username: admin
    password: adminpwd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console